name: DockerGC_data
on:
  push:
    paths:
    - 'data/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set variables
      run: |
        VER=$(cat data/VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: cd data && chmod +x b_data.sh && sh b_data.sh
    - name: Docker Push
      run: docker push siakbary/dockergc_data:${{env.VERSION}}