name: DockerGS GC Ubuntu (3.1) (Multi Platform)
on:
  push:
    paths:
    - 'gs/os-ubuntu-gc'
    - 'gs/ver_gc-3.1'
    - 'gs/entrypoint_gc.sh'
    - '.github/workflows/DockerGS_GC_Ubuntu_3.1.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync DockerGS
      uses: actions/checkout@v3
    - name: Sync Grasscutter Yuuki
      uses: actions/checkout@v3
      with:
       repository: akbaryahya/Grasscutter-Yuuki
       ref: "3.1"
       token: ${{ secrets.HUB_TOKEN }}
       path: gs/Grasscutter-Yuuki
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Get Version
      run: cd gs && chmod +x run.sh && sh run.sh ubuntu version 8
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
       context: ./gs
       file: ./gs/os-ubuntu-gc
       platforms: linux/amd64,linux/arm64,linux/arm/v7
       push: true
       tags: |
        ${{ env.ver1 }}
        ${{ env.ver2 }}
       cache-from: type=gha
       cache-to: type=gha,mode=max