name: DockerGC Alpine
on:
  push:
    paths:
    - 'gc/alpine'
    - 'gc/VERSION'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: true
    - name: Set variables
      run: |
        VER=$(cat gc/VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: cd gc && chmod +x run.sh && sh run.sh alpine
    - name: Push Docker image
      run: sh run.sh alpine push