name: DockerGC Debian
on:
  push:
    paths:
    - 'gc/debian'
    - 'gc/VERSION'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       submodules: true
    - name: Set variables
      run: |
        VER=$(cat gc/VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image & Push
      run: cd gc && chmod +x b_gc_d.sh && sh b_gc_d.sh push